apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-nginx-virtual-host-config
  namespace: default
data:
  default.conf: |

    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name localhost;

        root /usr/share/nginx/html;
        index index.html index.php;
        access_log /var/log/nginx/access.log custom-nginx;
        error_log /var/log/nginx/error.log;

        location = /healthz {
            add_header Content-Type text/plain;
            return 200 'ok';
        }

    }
